### ISSUE TITLE
registerTransformer error with spring basePackage=**/mapper

### ISSUE THREAD

**Issue by shpodg** [HotswapProjects/HotswapAgent#165] opened 2017-01-07 12:09 UTC
There will be throw regex Exception when ***basePackage*** to scan is configured with *****/mapper***.

```java
Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 2
^**/mapper.*$
  ^
	at java.util.regex.Pattern.error(Pattern.java:1955) ~[?:1.8.0_92]
	at java.util.regex.Pattern.sequence(Pattern.java:2123) ~[?:1.8.0_92]
	at java.util.regex.Pattern.expr(Pattern.java:1996) ~[?:1.8.0_92]
	at java.util.regex.Pattern.compile(Pattern.java:1696) ~[?:1.8.0_92]
	at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_92]
	at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_92]
	at org.hotswap.agent.util.HotswapTransformer.registerTransformer(HotswapTransformer.java:73) ~[hotswap-agent-1.0.jar:1.0]
```

**Comment by brandstaetter** [comment] 2017-05-09 17:48
duplicate of issue #78 ?

**Closed** 2017-05-22 19:57 UTC
Labels: bug
