### ISSUE TITLE
java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index

### ISSUE THREAD

**Issue by robshep** [HotswapProjects/HotswapAgent#256] opened 2018-07-10 00:03 UTC
Having just switched from jRebel to HotSwapAgent I get the following:

    java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index

I'm using `autoHotswap=true` 

I'm on a Mac using `jdk1.8.0_172` with the alternate VM deployment of DCE.

The Spring plugin reloads the beans and then when i do a page refresh I get this error on the console.

**Comment by robshep** [comment] 2018-07-10 00:04
Note: I'm not changing any Annotations for this, just method bodies of Spring MVC handlers that happen to have annotations.

**Comment by robshep** [comment] 2018-07-10 09:46
Yes, i'm running standalone outside of IDE as follows:

    ./mvnw clean spring-boot:run [...]

I'll prepare a test case, thanks

**Comment by MrABKhan** [comment] 2018-10-24 20:43
Try JDK 8u144 along with it's equivalent DCEVM. Solved the issue for me.

**Comment by skybber** [comment] 2018-10-27 09:41
Is this problem in JDK 8u152?

**Comment by robshep** [comment] 2018-11-15 00:08
I'm using 1.8.0_172 and the issue still occurs many times a day. 
I'm struggling to make a test case.  I have a large application and haven't managed to identify the sequence of events, or specific scenario that provokes a fault.

**Comment by skybber** [comment] 2018-11-15 07:58
Test case is not necessary. I'm pretty sure the problem is in current binaries but is already fixed in repository. The problem had been fixed in the past then unfortunately the fix was removed in 8u152, so 8u142 is the last fixed version. So we have to create new binaries!

**Comment by skybber** [comment] 2018-12-05 19:20
This dcevm issue, should be fixed in dcevm repository.

**Closed by skybber** 2018-12-05 19:20 UTC
