### ISSUE TITLE
autoHotSwap=true and JSP problem, caused Tomcat crash.

### ISSUE THREAD

**Issue by derekhsu** [HotswapProjects/HotswapAgent#88] opened 2015-07-24 07:36 UTC
HelIo, it's me again.

I add autoHotSwap=true property when I run a application in Eclipse, and I change a JSP file, then I got these message:

```
07-24 15:23:50 [INFO ] [DPMS] CoreContextPostProcessor - context [Root WebApplicationContext: startup date [Fri Jul 24 15:23:28 CST 2015]; root of context hierarchy] trigger application event [ServletRequestHandledEvent]
HOTSWAP AGENT: 15:23:50.745 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'org.apache.jasper.servlet.JasperLoader@b1255d'.
HOTSWAP AGENT: 15:23:50.804 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'org.apache.jasper.servlet.JasperLoader@a0a66d'.
HOTSWAP AGENT: 15:23:51.647 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'org.apache.jasper.servlet.JasperLoader@106f54c'.
HOTSWAP AGENT: 15:23:51.669 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'org.apache.jasper.servlet.JasperLoader@3bf49f'.
HOTSWAP AGENT: 15:23:55.791 ERROR (org.hotswap.agent.annotation.handler.WatchEventCommand) - Unable create CtClass for URI 'file:///D:/dpms/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/work/Catalina/localhost/xx/org/apache/jsp/WEB_002dINF/views/xx/demo/xxa1_jsp.classtmp'.
java.lang.IllegalArgumentException: java.io.FileNotFoundException: D:\dpms\workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\work\Catalina\localhost\xx\org\apache\jsp\WEB_002dINF\views\xx\demo\xxa1_jsp.classtmp (系統找不到指定的檔案。)
    at org.hotswap.agent.util.IOUtils.toByteArray(IOUtils.java:50)
    at org.hotswap.agent.annotation.handler.WatchEventCommand.createCtClass(WatchEventCommand.java:191)
    at org.hotswap.agent.annotation.handler.WatchEventCommand.onWatchEvent(WatchEventCommand.java:120)
    at org.hotswap.agent.annotation.handler.WatchEventCommand.executeCommand(WatchEventCommand.java:51)
    at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.io.FileNotFoundException: D:\dpms\workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\work\Catalina\localhost\xx\org\apache\jsp\WEB_002dINF\views\xx\demo\xxa1_jsp.classtmp (系統找不到指定的檔案。)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
    at java.net.URL.openStream(URL.java:1038)
    at org.hotswap.agent.util.IOUtils.toByteArray(IOUtils.java:44)
    ... 4 more
```

It seems it load a temp file when it run swap.
How can I avoid it? Or I have to run it on debug mode?

**Comment by skybber** [comment] 2015-08-30 06:23
Hi, I'm sorry for late answer. Could you create small test project please? It would help to solve the problem a lot.

**Comment by Troncoso** [comment] 2015-08-31 19:59
I'm getting this same error using hotswap agent, gwt, and maven. I have extraClassPath pointed to a dependency module. When I rebuild that module, it seems like hotswap recognizes the changes, but the log just shows the error above for each class in the module.

**Comment by skybber** [comment] 2015-09-01 11:07
The problem with loading not ".class" files should be fixed in 0.3 release (issue #55). Have you the same problem also in v0.3 ?

**Comment by fige135** [comment] 2015-09-23 01:08
I got the these problem in v0.3.
![image](https://cloud.githubusercontent.com/assets/3334311/10035869/b836a510-61d1-11e5-8b18-6d7b82472632.png)

>HOTSWAP AGENT: 8:59:38.960 ERROR (org.hotswap.agent.annotation.handler.WatchEventCommand) - Unable create CtClass for URI 'file:///D:/tools/apache-tomcat-7.0.42/work/Catalina/localhost/_/org/apache/jsp/index_jsp.class'.
java.lang.IllegalArgumentException: java.io.FileNotFoundException: D:\tools\apache-tomcat-7.0.42\work\Catalina\localhost\_\org\apache\jsp\index_jsp.class (系统找不到指定的路径。)
	at org.hotswap.agent.util.IOUtils.toByteArray(IOUtils.java:50)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.createCtClass(WatchEventCommand.java:191)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.onWatchEvent(WatchEventCommand.java:120)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.executeCommand(WatchEventCommand.java:51)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.io.FileNotFoundException: D:\tools\apache-tomcat-7.0.42\work\Catalina\localhost\_\org\apache\jsp\index_jsp.class (系统找不到指定的路径。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:101)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1037)
	at org.hotswap.agent.util.IOUtils.toByteArray(IOUtils.java:44)
	... 4 more

**Comment by skybber** [comment] 2015-09-26 08:18
This is not quite the same problem.In the original one case the agent failed when tries to load class from xyz.classtmp file. Classtmp is temporary class that is renamed to .class as I hope. Does this problem appear regulary or is it exceptional?

**Comment by yuke** [comment] 2016-07-06 12:09
According to my observation, every modification of JSP seems to trigger a new instance of JasperLoader to be loaded by a new instance of HotswapperPlugin, resulting eventual modification of the JSP class to trigger multiple reload of the same JSP class simultaneously, causing DCEVM to crash. The solution is to remove the WatchEventListener on the old JasperLoader but I have not found an easy way to do so yet.

By the way, if you are desperate, you can try this workaround for now. 
https://github.com/yuke/HotswapAgent/commit/98037e995c964ddc90ca4acf9332c316269264a9

**Comment by skybber** [comment] 2016-10-17 09:35
@yuke : I'm just preparing new 0.4 relase. It would be great if we find out some better way how to fix all the problems with jasper's JSP compilator. This should be in the new release. I can help with it but I need an example project. Could you please provide some minimal example project ?

**Comment by skybber** [comment] 2016-11-21 20:34
Fixed

**Closed by skybber** 2016-11-21 20:34 UTC
